# -*- coding: utf-8 -*-
"""NYCBUSSTOPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R7_TAW9tnp8un6MTjFdsbQR8KWN7RdPF
"""

!pip install geopandas folium mapclassify requests shapely -q

import requests
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, LineString
import folium
from folium.plugins import HeatMap
import warnings
import io, json, zipfile
warnings.filterwarnings("ignore")

# NYC 311 - filtered to flooding-related descriptors, last 3 years
# Socrata SoQL query - no API key needed for moderate volume
print("Fetching 311 flood complaints...")

url = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"
params = {
    "$where": (
        "created_date >= '2022-01-01T00:00:00' "
        "AND (descriptor LIKE '%Flood%' OR descriptor LIKE '%flood%' "
        "OR complaint_type LIKE '%Sewer%' OR descriptor LIKE '%Water%') "
        "AND latitude IS NOT NULL"
    ),
    "$limit": 50000,
    "$select": "unique_key, created_date, complaint_type, descriptor, latitude, longitude, borough, incident_zip"
}

resp = requests.get(url, params=params)
df_311 = pd.DataFrame(resp.json())
print(f"  Fetched {len(df_311):,} records")

# Cast coords
df_311["latitude"] = pd.to_numeric(df_311["latitude"])
df_311["longitude"] = pd.to_numeric(df_311["longitude"])
df_311 = df_311.dropna(subset=["latitude","longitude"])

# Convert to GeoDataFrame
gdf_311 = gpd.GeoDataFrame(
    df_311,
    geometry=gpd.points_from_xy(df_311.longitude, df_311.latitude),
    crs="EPSG:4326"
)
print(f"  Valid points: {len(gdf_311):,}")
gdf_311.head(3)

print("Fetching MTA Bus GTFS (borough files)...")

BUS_GTFS_URLS = [
    ("Bronx",         "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_bx.zip"),
    ("Brooklyn",      "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_b.zip"),
    ("Manhattan",     "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_m.zip"),
    ("Queens",        "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_q.zip"),
    ("Staten Island", "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_si.zip"),
    ("MTA Bus Co",    "https://rrgtfsfeeds.s3.amazonaws.com/gtfs_busco.zip"),
]

# S3 blocks requests without a browser user-agent
HEADERS = {"User-Agent": "Mozilla/5.0 (compatible; research-script/1.0)"}

all_stops      = []
all_trips      = []
all_routes     = []
all_stop_times = []

for name, url in BUS_GTFS_URLS:
    print(f"  Downloading {name}...")
    try:
        resp = requests.get(url, headers=HEADERS, timeout=120)
        resp.raise_for_status()
        zip_bytes = io.BytesIO(resp.content)

        with zipfile.ZipFile(zip_bytes) as z:
            stops      = pd.read_csv(z.open("stops.txt"))
            trips      = pd.read_csv(z.open("trips.txt"))
            routes     = pd.read_csv(z.open("routes.txt"))
            stop_times = pd.read_csv(z.open("stop_times.txt"),
                                     usecols=["trip_id","stop_id"])

        stops["source"]  = name
        routes["source"] = name

        all_stops.append(stops)
        all_trips.append(trips)
        all_routes.append(routes)
        all_stop_times.append(stop_times)

        print(f"    {len(stops):,} stops | {len(routes):,} routes")

    except Exception as e:
        print(f"    Failed: {e}")

if not all_stops:
    raise RuntimeError("All GTFS feeds failed")

df_stops      = pd.concat(all_stops,      ignore_index=True).drop_duplicates("stop_id")
df_trips      = pd.concat(all_trips,      ignore_index=True).drop_duplicates("trip_id")
df_routes     = pd.concat(all_routes,     ignore_index=True).drop_duplicates("route_id")
df_stop_times = pd.concat(all_stop_times, ignore_index=True).drop_duplicates()

print(f"\nTotal: {len(df_stops):,} stops | {len(df_routes):,} routes")

# Build stop → route lookup
stop_trip  = df_stop_times.merge(df_trips[["trip_id","route_id"]], on="trip_id", how="left")
stop_route = stop_trip[["stop_id","route_id"]].drop_duplicates()
stop_route = stop_route.merge(
    df_routes[["route_id","route_short_name","route_long_name"]],
    on="route_id", how="left"
)

df_stops_full = df_stops[["stop_id","stop_lat","stop_lon"]].merge(
    stop_route, on="stop_id", how="left"
)
df_stops_full = df_stops_full.dropna(subset=["stop_lat","stop_lon","route_short_name"])

gdf_stops = gpd.GeoDataFrame(
    df_stops_full,
    geometry=gpd.points_from_xy(df_stops_full.stop_lon, df_stops_full.stop_lat),
    crs="EPSG:4326"
)
gdf_stops["rt_symbol"] = gdf_stops["route_short_name"].str.strip()

print(f"\nStops with route assignment: {len(gdf_stops):,}")
print(f"Unique bus routes: {gdf_stops['rt_symbol'].nunique()}")
gdf_stops.head(3)

print("Fetching FEMA flood zones for NYC via ArcGIS REST...")

base_url = "https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28/query"

all_features = []
offset = 0
batch = 1000
nyc_bbox = "-74.26,40.49,-73.69,40.92"

while True:
    params = {
        "where": "1=1",
        "geometry": nyc_bbox,
        "geometryType": "esriGeometryEnvelope",
        "spatialRel": "esriSpatialRelIntersects",
        "inSR": "4326",
        "outFields": "FLD_ZONE,ZONE_SUBTY,SFHA_TF",
        "outSR": "4326",
        "f": "geojson",
        "resultOffset": offset,
        "resultRecordCount": batch
    }
    r = requests.get(base_url, params=params, timeout=60)
    try:
        data = json.loads(r.text)
    except json.JSONDecodeError as e:
        print(f"JSON parse error: {e}")
        break

    feats = data.get("features", [])
    print(f"  Batch at offset {offset}: {len(feats)} features")

    if not feats:
        break

    all_features.extend(feats)

    if len(feats) < batch:
        break
    offset += batch

print(f"\nTotal features fetched: {len(all_features)}")

geojson = {"type": "FeatureCollection", "features": all_features}
gdf_fema = gpd.read_file(io.StringIO(json.dumps(geojson)))
gdf_fema = gdf_fema.to_crs("EPSG:4326")

if "FLD_ZONE" in gdf_fema.columns:
    gdf_fema = gdf_fema.rename(columns={"FLD_ZONE": "fld_zone"})

print(f"FEMA zones loaded: {len(gdf_fema)} features")
print(f"Zone types: {gdf_fema['fld_zone'].unique()}")

LOCAL_CRS = "EPSG:2263"

gdf_311_proj   = gdf_311.to_crs(LOCAL_CRS)
gdf_stops_proj = gdf_stops.to_crs(LOCAL_CRS)
gdf_fema_proj  = gdf_fema.to_crs(LOCAL_CRS)

print("All layers reprojected to EPSG:2263")
print(f"Bus stops: {len(gdf_stops_proj):,}")

BUFFER_FEET = 300  # tighter than subway — stops are dense

print(f"Buffering bus stops by {BUFFER_FEET} ft and counting 311 complaints...")

# Buffer each stop
gdf_stops_proj["buffer_geom"] = gdf_stops_proj.geometry.buffer(BUFFER_FEET)

# One buffer GDF
gdf_buf = gpd.GeoDataFrame(
    gdf_stops_proj[["stop_id","rt_symbol","buffer_geom"]].copy(),
    geometry="buffer_geom",
    crs=LOCAL_CRS
)

# Spatial join 311 points to stop buffers
print("  Running spatial join (may take 1-2 min with this many stops)...")
joined = gpd.sjoin(
    gdf_311_proj[["geometry"]].copy(),
    gdf_buf,
    how="inner",
    predicate="within"
)

print(f"  Joined records: {len(joined):,}")

# Aggregate to route level
counts_dict = joined.groupby("rt_symbol").size().to_dict()
print(f"  Routes with complaints: {len(counts_dict)}")

# One row per route with total complaints
route_summary = pd.DataFrame([
    {"rt_symbol": k, "flood_complaints": v}
    for k, v in counts_dict.items()
]).sort_values("flood_complaints", ascending=False)

print(f"\nTop 20 bus routes by flood complaints:")
print(route_summary.head(20).to_string(index=False))

# Dissolve FEMA A zones
fema_high_risk = gdf_fema_proj[gdf_fema_proj["fld_zone"].str.startswith("A", na=False)].copy()
fema_dissolved = fema_high_risk.dissolve()

# Representative point per route (median stop location)
route_centroids = gdf_stops_proj.groupby("rt_symbol").apply(
    lambda g: g.geometry.unary_union.centroid
).reset_index()
route_centroids.columns = ["rt_symbol", "centroid"]

gdf_route_cents = gpd.GeoDataFrame(route_centroids, geometry="centroid", crs=LOCAL_CRS)

in_flood = gpd.sjoin(
    gdf_route_cents,
    fema_dissolved[["geometry"]],
    how="left",
    predicate="within"
)
in_flood["in_fema_zone"] = in_flood["index_right"].notna()

# Merge everything into final summary
route_summary = route_summary.merge(
    in_flood[["rt_symbol","in_fema_zone"]].drop_duplicates("rt_symbol"),
    on="rt_symbol", how="left"
)
route_summary["in_fema_zone"] = route_summary["in_fema_zone"].fillna(False)

anomalies = route_summary[~route_summary["in_fema_zone"]].copy()

print(f"Total bus routes analyzed: {len(route_summary)}")
print(f"Outside FEMA zone: {(~route_summary['in_fema_zone']).sum()}")
print(f"\nTop 15 outside flood zone:")
print(anomalies.head(15).to_string(index=False))

# Reproject stops to WGS84 for folium
gdf_stops_wgs = gdf_stops_proj.drop(columns=["buffer_geom"]).to_crs("EPSG:4326")
gdf_fema_wgs  = gdf_fema_proj.to_crs("EPSG:4326")
gdf_fema_high = gdf_fema_wgs[gdf_fema_wgs["fld_zone"].str.startswith("A", na=False)].copy()
gdf_fema_high["fld_zone"] = gdf_fema_high["fld_zone"].astype(str)

# Top 20 anomaly routes for highlighting
top_routes = set(anomalies.head(20)["rt_symbol"].tolist())

m = folium.Map(location=[40.73, -73.95], zoom_start=11, tiles="CartoDB dark_matter")

# FEMA flood zones
folium.GeoJson(
    json.loads(gdf_fema_high.to_json()),
    name="FEMA Flood Zones (A)",
    style_function=lambda x: {
        "fillColor": "#4488ff",
        "color": "#2244cc",
        "weight": 0.5,
        "fillOpacity": 0.25
    }
).add_to(m)

# 311 heatmap
heat_data = [[row.latitude, row.longitude] for _, row in gdf_311.iterrows()]
HeatMap(heat_data, name="311 Flood Complaints",
        radius=10, blur=15, min_opacity=0.3).add_to(m)

# Bus stops — color by whether route is a top anomaly
normal_layer = folium.FeatureGroup(name="All Bus Stops")
anomaly_layer = folium.FeatureGroup(name="Top 20 Flood Anomaly Routes")

sample_stops = gdf_stops_wgs.drop_duplicates("stop_id")

for _, row in sample_stops.iterrows():
    rt = str(row.get("rt_symbol",""))
    lat, lon = row.geometry.y, row.geometry.x
    complaints = counts_dict.get(rt, 0)

    if rt in top_routes:
        folium.CircleMarker(
            location=[lat, lon],
            radius=4,
            color="#ff6600",
            fill=True,
            fill_color="#ff6600",
            fill_opacity=0.8,
            tooltip=f"Route {rt} | {complaints:,} complaints"
        ).add_to(anomaly_layer)
    else:
        folium.CircleMarker(
            location=[lat, lon],
            radius=2,
            color="#888888",
            fill=True,
            fill_color="#888888",
            fill_opacity=0.4,
        ).add_to(normal_layer)

normal_layer.add_to(m)
anomaly_layer.add_to(m)
folium.LayerControl().add_to(m)

m.save("nyc_bus_flood_anomalies.html")
print("Map saved to nyc_bus_flood_anomalies.html")
m

MTA_BUS_COLOR = "#0039A6"  # MTA blue for all bus routes

rows_html = ""
for i, row in anomalies.head(30).iterrows():
    rt = str(row["rt_symbol"])
    complaints = int(row["flood_complaints"])
    bar_pct = int(complaints / anomalies["flood_complaints"].max() * 100)
    rows_html += f"""
    <tr style="border-bottom:0.5px solid #e0e0e0;">
      <td style="padding:7px 14px;width:60px;">
        <div style="background:{MTA_BUS_COLOR};color:#fff;
            border-radius:4px;padding:3px 7px;
            font-size:11px;font-weight:700;font-family:sans-serif;
            display:inline-block;white-space:nowrap;">
          {rt}
        </div>
      </td>
      <td style="padding:7px 14px;">
        <div style="background:#eeeeee;border-radius:3px;height:8px;width:100%;max-width:260px;">
          <div style="background:{MTA_BUS_COLOR};width:{bar_pct}%;height:8px;
              border-radius:3px;opacity:0.75;"></div>
        </div>
      </td>
      <td style="padding:7px 14px;text-align:right;
          font-variant-numeric:tabular-nums;font-size:14px;color:#333;">
        {complaints:,}
      </td>
    </tr>"""

html_table = f"""
<style>
  .flood-table {{ width:100%;border-collapse:collapse;font-family:sans-serif;font-size:14px; }}
  .flood-table tr:hover td {{ background:#f9f9f9; }}
</style>
<table class="flood-table">
  <thead>
    <tr style="border-bottom:2px solid #ccc;">
      <th style="padding:8px 14px;text-align:left;font-size:12px;
          color:#666;font-weight:500;">Route</th>
      <th style="padding:8px 14px;text-align:left;font-size:12px;
          color:#666;font-weight:500;">311 Flood Complaints (2022–present)</th>
      <th style="padding:8px 14px;text-align:right;font-size:12px;
          color:#666;font-weight:500;">Count</th>
    </tr>
  </thead>
  <tbody>{rows_html}</tbody>
</table>
"""

from IPython.display import HTML
display(HTML(html_table))