# -*- coding: utf-8 -*-
"""NYCSybwayFlood.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1tJzV14moB0kMErJI69WZLd9yy9EQd9
"""

!pip install geopandas folium mapclassify requests shapely -q



import requests
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import folium
from folium.plugins import HeatMap
import warnings
warnings.filterwarnings("ignore")

# NYC 311 - filtered to flooding-related descriptors, last 3 years
# Socrata SoQL query - no API key needed for moderate volume
print("Fetching 311 flood complaints...")

url = "https://data.cityofnewyork.us/resource/erm2-nwe9.json"
params = {
    "$where": (
        "created_date >= '2022-01-01T00:00:00' "
        "AND (descriptor LIKE '%Flood%' OR descriptor LIKE '%flood%' "
        "OR complaint_type LIKE '%Sewer%' OR descriptor LIKE '%Water%') "
        "AND latitude IS NOT NULL"
    ),
    "$limit": 50000,
    "$select": "unique_key, created_date, complaint_type, descriptor, latitude, longitude, borough, incident_zip"
}

resp = requests.get(url, params=params)
df_311 = pd.DataFrame(resp.json())
print(f"  Fetched {len(df_311):,} records")

# Cast coords
df_311["latitude"] = pd.to_numeric(df_311["latitude"])
df_311["longitude"] = pd.to_numeric(df_311["longitude"])
df_311 = df_311.dropna(subset=["latitude","longitude"])

# Convert to GeoDataFrame
gdf_311 = gpd.GeoDataFrame(
    df_311,
    geometry=gpd.points_from_xy(df_311.longitude, df_311.latitude),
    crs="EPSG:4326"
)
print(f"  Valid points: {len(gdf_311):,}")
gdf_311.head(3)

import io, zipfile, urllib.request
from shapely.geometry import LineString

print("Fetching MTA subway routes from GTFS...")

# MTA official GTFS static feed
GTFS_URL = "http://web.mta.info/developers/data/nyct/subway/google_transit.zip"

# Download zip into memory
with urllib.request.urlopen(GTFS_URL) as resp:
    zip_bytes = io.BytesIO(resp.read())

print("  Downloaded GTFS zip")

with zipfile.ZipFile(zip_bytes) as z:
    shapes = pd.read_csv(z.open("shapes.txt"))
    trips  = pd.read_csv(z.open("trips.txt"))
    routes = pd.read_csv(z.open("routes.txt"))

print(f"  shapes: {len(shapes):,} rows | trips: {len(trips):,} | routes: {len(routes):,}")

# Build LineString per shape_id
def build_lines(df):
    df = df.sort_values("shape_pt_sequence")
    coords = list(zip(df["shape_pt_lon"], df["shape_pt_lat"]))
    return LineString(coords) if len(coords) >= 2 else None

print("  Building LineStrings from shape points (may take ~30s)...")
lines = shapes.groupby("shape_id").apply(build_lines).reset_index()
lines.columns = ["shape_id", "geometry"]
lines = lines[lines["geometry"].notna()]

# Join shape_id → route via trips
shape_route = trips[["shape_id","route_id"]].drop_duplicates("shape_id")
lines = lines.merge(shape_route, on="shape_id", how="left")

# Join route_id → route name/color
lines = lines.merge(
    routes[["route_id","route_short_name","route_long_name","route_color"]],
    on="route_id", how="left"
)

# Make GeoDataFrame
gdf_subway = gpd.GeoDataFrame(lines, geometry="geometry", crs="EPSG:4326")
gdf_subway["name"] = gdf_subway["route_long_name"].fillna(gdf_subway["route_short_name"])
gdf_subway["rt_symbol"] = gdf_subway["route_short_name"]

print(f"  Subway lines built: {len(gdf_subway)} shape segments")
print(f"  Routes: {sorted(gdf_subway['rt_symbol'].dropna().unique())}")
gdf_subway.head(3)

import io, json

print("Fetching FEMA flood zones for NYC via ArcGIS REST...")

base_url = "https://hazards.fema.gov/arcgis/rest/services/public/NFHL/MapServer/28/query"

all_features = []
offset = 0
batch = 1000
nyc_bbox = "-74.26,40.49,-73.69,40.92"

while True:
    params = {
        "where": "1=1",
        "geometry": nyc_bbox,
        "geometryType": "esriGeometryEnvelope",
        "spatialRel": "esriSpatialRelIntersects",
        "inSR": "4326",
        "outFields": "FLD_ZONE,ZONE_SUBTY,SFHA_TF",
        "outSR": "4326",
        "f": "geojson",
        "resultOffset": offset,
        "resultRecordCount": batch
    }

    r = requests.get(base_url, params=params, timeout=60)

    # Force parse regardless of content-type header
    try:
        data = json.loads(r.text)
    except json.JSONDecodeError as e:
        print(f"JSON parse error: {e}")
        break

    feats = data.get("features", [])
    print(f"  Batch at offset {offset}: {len(feats)} features")

    if not feats:
        break

    all_features.extend(feats)

    if len(feats) < batch:
        break
    offset += batch

print(f"\nTotal features fetched: {len(all_features)}")

# Build GeoDataFrame
geojson = {"type": "FeatureCollection", "features": all_features}
gdf_fema = gpd.read_file(io.StringIO(json.dumps(geojson)))
gdf_fema = gdf_fema.to_crs("EPSG:4326")

if "FLD_ZONE" in gdf_fema.columns:
    gdf_fema = gdf_fema.rename(columns={"FLD_ZONE": "fld_zone"})

print(f"FEMA zones loaded: {len(gdf_fema)} features")
print(f"Zone types: {gdf_fema['fld_zone'].unique()}")
gdf_fema.head(3)

# EPSG:2263 = NY State Plane, feet — good for NYC buffering
LOCAL_CRS = "EPSG:2263"

gdf_311_proj     = gdf_311.to_crs(LOCAL_CRS)
gdf_subway_proj  = gdf_subway.to_crs(LOCAL_CRS)
gdf_fema_proj    = gdf_fema.to_crs(LOCAL_CRS)

print("All layers reprojected to EPSG:2263")

BUFFER_FEET = 400

print(f"Buffering subway routes by {BUFFER_FEET} ft...")

# Dissolve to one geometry per route
gdf_subway_dissolved = gdf_subway_proj.dissolve(by="rt_symbol").reset_index()
gdf_subway_dissolved["name"] = gdf_subway_dissolved["rt_symbol"]

# Buffer in projected CRS
gdf_subway_dissolved["buffer_geom"] = gdf_subway_dissolved.geometry.buffer(BUFFER_FEET)

# Build a separate GDF with buffer as active geometry
gdf_buf = gpd.GeoDataFrame(
    gdf_subway_dissolved[["rt_symbol", "buffer_geom"]].copy(),
    geometry="buffer_geom",
    crs=LOCAL_CRS
)

print(f"  Routes to buffer: {len(gdf_buf)}")

# Spatial join
joined = gpd.sjoin(
    gdf_311_proj[["geometry"]].copy(),
    gdf_buf,
    how="inner",
    predicate="within"
)

print(f"  Joined records: {len(joined)}")

# Count per route into a plain dict
counts_dict = joined.groupby("rt_symbol").size().to_dict()
print(f"  Routes with complaints: {len(counts_dict)}")

# Assign directly — no merge needed
gdf_subway_dissolved["flood_complaints"] = (
    gdf_subway_dissolved["rt_symbol"].map(counts_dict).fillna(0).astype(int)
)

print("\nFinal complaint counts per route:")
print(
    gdf_subway_dissolved[["rt_symbol", "flood_complaints"]]
    .sort_values("flood_complaints", ascending=False)
    .to_string(index=False)
)

gdf_subway_proj = gdf_subway_dissolved

# Dissolve flood zones to single polygon
fema_high_risk = gdf_fema_proj[gdf_fema_proj["fld_zone"].str.startswith("A", na=False)].copy()
fema_dissolved = fema_high_risk.dissolve()

# Centroid of each subway line for zone check
gdf_subway_proj["centroid"] = gdf_subway_proj.geometry.centroid
gdf_subway_cents = gdf_subway_proj.copy().set_geometry("centroid")

# Which centroids fall INSIDE flood zone?
in_flood = gpd.sjoin(
    gdf_subway_cents[["name","centroid","flood_complaints"]],
    fema_dissolved[["geometry"]],
    how="left",
    predicate="within"
)
in_flood["in_fema_zone"] = in_flood["index_right"].notna()

gdf_subway_proj = gdf_subway_proj.merge(
    in_flood[["name","in_fema_zone"]].drop_duplicates("name"),
    on="name", how="left"
)

# THE KEY FILTER: outside flood zone but high complaints
median_complaints = gdf_subway_proj["flood_complaints"].median()
gdf_anomalies = gdf_subway_proj[
    (~gdf_subway_proj["in_fema_zone"]) &
    (gdf_subway_proj["flood_complaints"] > median_complaints)
].copy()

print(f"\n=== ANOMALY ROUTES ===")
print(f"Outside FEMA zone but above-median flood complaints: {len(gdf_anomalies)}")
print(gdf_anomalies[["name","rt_symbol","flood_complaints"]].sort_values("flood_complaints", ascending=False))

# Drop non-serializable geometry columns
for col in ["buffer_geom", "centroid"]:
    for gdf in [gdf_subway_proj, gdf_anomalies]:
        if col in gdf.columns:
            gdf.drop(columns=[col], inplace=True)

# Reproject to WGS84
gdf_subway_wgs  = gdf_subway_proj.set_geometry("geometry").to_crs("EPSG:4326")
gdf_anomaly_wgs = gdf_anomalies.set_geometry("geometry").to_crs("EPSG:4326")
gdf_fema_wgs    = gdf_fema_proj.to_crs("EPSG:4326")

# Official MTA route colors
MTA_COLORS = {
    "1":"#EE352E","2":"#EE352E","3":"#EE352E",
    "4":"#00933C","5":"#00933C","6":"#00933C","6X":"#00933C",
    "7":"#B933AD","7X":"#B933AD",
    "A":"#0039A6","C":"#0039A6","E":"#0039A6",
    "B":"#FF6319","D":"#FF6319","F":"#FF6319","FX":"#FF6319","M":"#FF6319",
    "G":"#6CBE45",
    "J":"#996633","Z":"#996633",
    "L":"#A7A9AC",
    "N":"#FCCC0A","Q":"#FCCC0A","R":"#FCCC0A","W":"#FCCC0A",
    "S":"#808183",
    "SIR":"#0039A6",
}

def clean_for_folium(gdf):
    gdf = gdf.copy()
    for col in gdf.columns:
        if col == gdf.geometry.name:
            continue
        if len(gdf) > 0 and hasattr(gdf[col].iloc[0], '__geo_interface__'):
            gdf = gdf.drop(columns=[col])
            continue
        if gdf[col].dtype == object:
            try:
                gdf[col] = gdf[col].astype(str)
            except:
                gdf = gdf.drop(columns=[col])
    return gdf

gdf_subway_wgs  = clean_for_folium(gdf_subway_wgs)
gdf_anomaly_wgs = clean_for_folium(gdf_anomaly_wgs)
gdf_fema_high   = clean_for_folium(
    gdf_fema_wgs[gdf_fema_wgs["fld_zone"].str.startswith("A", na=False)]
)

m = folium.Map(location=[40.73, -73.95], zoom_start=11, tiles="CartoDB dark_matter")

# FEMA flood zones
folium.GeoJson(
    gdf_fema_high.to_json(),
    name="FEMA Flood Zones (A)",
    style_function=lambda x: {
        "fillColor": "#4488ff",
        "color": "#2244cc",
        "weight": 0.5,
        "fillOpacity": 0.25
    }
).add_to(m)

# All subway routes colored by MTA route color
def subway_style(feature):
    rt = feature["properties"].get("rt_symbol", "")
    color = MTA_COLORS.get(rt, "#aaaaaa")
    return {"color": color, "weight": 3, "opacity": 0.85}

folium.GeoJson(
    gdf_subway_wgs.to_json(),
    name="All Subway Routes",
    style_function=subway_style,
    tooltip=folium.GeoJsonTooltip(
        fields=["rt_symbol", "flood_complaints"],
        aliases=["Line", "311 Flood Complaints"],
        sticky=True
    )
).add_to(m)

# Anomaly routes — thick white outline + MTA color on top for visibility
def anomaly_style(feature):
    rt = feature["properties"].get("rt_symbol", "")
    color = MTA_COLORS.get(rt, "#ff6600")
    return {"color": color, "weight": 7, "opacity": 1.0}

# White halo layer underneath anomalies
folium.GeoJson(
    gdf_anomaly_wgs.to_json(),
    name="Anomaly halo",
    style_function=lambda x: {"color": "#ffffff", "weight": 11, "opacity": 0.4}
).add_to(m)

folium.GeoJson(
    gdf_anomaly_wgs.to_json(),
    name="Outside Flood Zone — High 311 Flooding",
    style_function=anomaly_style,
    tooltip=folium.GeoJsonTooltip(
        fields=["rt_symbol", "flood_complaints"],
        aliases=["Line", "311 Flood Complaints"],
        sticky=True
    )
).add_to(m)

# 311 heatmap
heat_data = [[row.latitude, row.longitude] for _, row in gdf_311.iterrows()]
HeatMap(heat_data, name="311 Flood Complaints", radius=10, blur=15, min_opacity=0.3).add_to(m)

# Route label markers at line midpoints
label_layer = folium.FeatureGroup(name="Route Labels")
for _, row in gdf_subway_wgs.iterrows():
    rt = str(row.get("rt_symbol", ""))
    if not rt or rt == "nan":
        continue
    try:
        mid = row.geometry.interpolate(0.5, normalized=True)
        color = MTA_COLORS.get(rt, "#aaaaaa")
        folium.Marker(
            location=[mid.y, mid.x],
            icon=folium.DivIcon(
                html=f'''<div style="
                    background:{color};
                    color:{'#000' if rt in ['N','Q','R','W'] else '#fff'};
                    border-radius:50%;
                    width:22px;height:22px;
                    display:flex;align-items:center;justify-content:center;
                    font-size:11px;font-weight:bold;
                    border:2px solid rgba(255,255,255,0.6);
                    font-family:sans-serif;
                ">{rt}</div>''',
                icon_size=(22, 22),
                icon_anchor=(11, 11)
            )
        ).add_to(label_layer)
    except:
        continue

label_layer.add_to(m)
folium.LayerControl().add_to(m)

m.save("nyc_mta_flood_anomalies.html")
print("Map saved to nyc_mta_flood_anomalies.html")
m

summary = gdf_subway_proj[["name","rt_symbol","flood_complaints","in_fema_zone"]]\
    .sort_values("flood_complaints", ascending=False)\
    .reset_index(drop=True)

summary["in_fema_zone"] = summary["in_fema_zone"].map({True:"Yes", False:"No"})
summary.columns = ["Line Name","Routes","311 Flood Complaints","In FEMA Flood Zone?"]
print(summary.to_string(index=False))

print("Building NYC borough boundaries from hardcoded GeoJSON...")

# Official NYC borough boundaries (simplified, hardcoded — they never change)
nyc_boroughs_geojson = {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {"boro_name": "Manhattan"},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-74.0479, 40.6829], [-73.9067, 40.7823], [-73.9333, 40.8512],
          [-73.9100, 40.8783], [-73.9279, 40.8785], [-73.9557, 40.8579],
          [-74.0185, 40.6998], [-74.0479, 40.6829]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {"boro_name": "Brooklyn"},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-74.0421, 40.5707], [-73.9331, 40.5773], [-73.8330, 40.6579],
          [-73.8780, 40.6823], [-73.9800, 40.6957], [-74.0421, 40.5707]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {"boro_name": "Queens"},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-73.9624, 40.5730], [-73.7002, 40.5730], [-73.7002, 40.8000],
          [-73.8330, 40.8000], [-73.9624, 40.7200], [-73.9624, 40.5730]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {"boro_name": "Bronx"},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-73.9333, 40.7960], [-73.7650, 40.7960], [-73.7650, 40.9176],
          [-73.9333, 40.9176], [-73.9333, 40.7960]
        ]]
      }
    },
    {
      "type": "Feature",
      "properties": {"boro_name": "Staten Island"},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[
          [-74.2591, 40.4960], [-74.0334, 40.4960], [-74.0334, 40.6499],
          [-74.2591, 40.6499], [-74.2591, 40.4960]
        ]]
      }
    }
  ]
}

gdf_boros = gpd.GeoDataFrame.from_features(nyc_boroughs_geojson["features"])
gdf_boros = gdf_boros.set_crs("EPSG:4326").to_crs("EPSG:2263")

print(f"  Boroughs loaded: {gdf_boros['boro_name'].tolist()}")

# Get midpoint of each route
gdf_subway_proj["midpoint"] = gdf_subway_proj.geometry.interpolate(0.5, normalized=True)
gdf_mids = gpd.GeoDataFrame(
    gdf_subway_proj[["rt_symbol", "flood_complaints", "midpoint"]].copy(),
    geometry="midpoint",
    crs="EPSG:2263"
)

# Spatial join midpoints to boroughs
gdf_mids = gpd.sjoin(
    gdf_mids,
    gdf_boros[["boro_name", "geometry"]],
    how="left",
    predicate="within"
)
gdf_mids["boro_name"] = gdf_mids["boro_name"].fillna("Multi-borough")

# Merge back
boro_lookup = gdf_mids[["rt_symbol", "boro_name"]].drop_duplicates("rt_symbol")
gdf_subway_proj = gdf_subway_proj.merge(boro_lookup, on="rt_symbol", how="left")
gdf_subway_proj["boro_name"] = gdf_subway_proj["boro_name"].fillna("Multi-borough")

print("\nRoutes by borough:")
print(gdf_subway_proj[["rt_symbol", "boro_name", "flood_complaints"]]
      .sort_values(["boro_name", "flood_complaints"], ascending=[True, False])
      .to_string(index=False))

# MTA colors for bullet rendering
MTA_COLORS = {
    "1":"#EE352E","2":"#EE352E","3":"#EE352E",
    "4":"#00933C","5":"#00933C","6":"#00933C","6X":"#00933C",
    "7":"#B933AD","7X":"#B933AD",
    "A":"#0039A6","C":"#0039A6","E":"#0039A6",
    "B":"#FF6319","D":"#FF6319","F":"#FF6319","FX":"#FF6319","M":"#FF6319",
    "G":"#6CBE45",
    "J":"#996633","Z":"#996633",
    "L":"#A7A9AC",
    "N":"#FCCC0A","Q":"#FCCC0A","R":"#FCCC0A","W":"#FCCC0A",
    "S":"#808183",
    "SIR":"#0039A6",
}

LIGHT_TEXT = {"N","Q","R","W"}  # dark text on yellow

summary = gdf_subway_proj[["rt_symbol","flood_complaints","boro_name"]]\
    .sort_values(["boro_name","flood_complaints"], ascending=[True,False])\
    .reset_index(drop=True)

# Build HTML table
boro_order = ["Bronx","Brooklyn","Manhattan","Queens","Staten Island","Multi-borough"]
summary["boro_name"] = pd.Categorical(summary["boro_name"], categories=boro_order, ordered=True)
summary = summary.sort_values(["boro_name","flood_complaints"], ascending=[True,False])

BORO_COLORS = {
    "Bronx":         ("#FFF3E0", "#E65100"),
    "Brooklyn":      ("#E8F5E9", "#2E7D32"),
    "Manhattan":     ("#E3F2FD", "#1565C0"),
    "Queens":        ("#F3E5F5", "#6A1B9A"),
    "Staten Island": ("#FCE4EC", "#880E4F"),
    "Multi-borough": ("#F5F5F5", "#424242"),
}

rows_html = ""
current_boro = None
for _, row in summary.iterrows():
    rt = row["rt_symbol"]
    complaints = int(row["flood_complaints"])
    boro = row["boro_name"] if pd.notna(row["boro_name"]) else "Multi-borough"
    bg_color, text_color = BORO_COLORS.get(boro, ("#F5F5F5","#424242"))
    mta_color = MTA_COLORS.get(rt, "#aaaaaa")
    bullet_text_color = "#000000" if rt in LIGHT_TEXT else "#ffffff"

    if boro != current_boro:
        current_boro = boro
        rows_html += f"""
        <tr>
          <td colspan="3" style="background:{bg_color};color:{text_color};
              font-weight:600;font-size:13px;padding:8px 14px;
              border-top:2px solid {text_color}22;letter-spacing:0.04em;">
            {boro.upper()}
          </td>
        </tr>"""

    # Bar width scaled to max
    bar_pct = int(complaints / 1167 * 100)
    rows_html += f"""
    <tr style="border-bottom:0.5px solid #e0e0e0;">
      <td style="padding:7px 14px;width:52px;">
        <div style="width:26px;height:26px;border-radius:50%;
            background:{mta_color};color:{bullet_text_color};
            display:flex;align-items:center;justify-content:center;
            font-size:11px;font-weight:700;font-family:sans-serif;">
          {rt}
        </div>
      </td>
      <td style="padding:7px 14px;">
        <div style="background:#eeeeee;border-radius:3px;height:8px;width:100%;max-width:260px;">
          <div style="background:{mta_color};width:{bar_pct}%;height:8px;border-radius:3px;opacity:0.85;"></div>
        </div>
      </td>
      <td style="padding:7px 14px;text-align:right;font-variant-numeric:tabular-nums;
          font-size:14px;color:#333;min-width:60px;">
        {complaints:,}
      </td>
    </tr>"""

html_table = f"""
<style>
  .flood-table {{ width:100%;border-collapse:collapse;font-family:sans-serif;font-size:14px; }}
  .flood-table tr:hover td {{ background:#f9f9f9; }}
</style>
<table class="flood-table">
  <thead>
    <tr style="border-bottom:2px solid #ccc;">
      <th style="padding:8px 14px;text-align:left;font-size:12px;color:#666;font-weight:500;">Line</th>
      <th style="padding:8px 14px;text-align:left;font-size:12px;color:#666;font-weight:500;">311 Flood Complaints (2022–present)</th>
      <th style="padding:8px 14px;text-align:right;font-size:12px;color:#666;font-weight:500;">Count</th>
    </tr>
  </thead>
  <tbody>{rows_html}</tbody>
</table>
"""

from IPython.display import HTML
display(HTML(html_table))