# -*- coding: utf-8 -*-
"""NG_Leak_Detection_RyanKmetz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBx-1kWUPUpL41hDeH7KdevBnl_gGHTd

# 🛢️ Natural Gas Leak Detection — Hyperspectral Imagery
## Vegetation Stress (Pipeline A) + SWIR CH₄ Enhancement (Pipeline B)

---

```
MIT License

Copyright (c) 2025 Ryan Kmetz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
```

---

**Author:** Ryan Kmetz  
**Pipelines:**
- **Pipeline A** — Vegetation Stress via Vegetation Indices (VI) + DNN *(Ma et al., 2024)*
- **Pipeline B** — SWIR CH₄ Enhancement via EMIT L2B + Matched Filter *(DigitalSense AI, 2025)*

**Data Sources:**
- [NASA EMIT L2B CH4 Enhancement V002](https://lpdaac.usgs.gov/products/emitl2bch4enhv002/)
- [NASA EMIT L2A Reflectance V001](https://lpdaac.usgs.gov/products/emitl2arflv001/)

## Step 1 — Install Dependencies
"""

!pip install earthaccess rasterio numpy matplotlib scipy scikit-image \
           folium ipyleaflet netCDF4 scikit-learn -q
print("✅ All dependencies installed.")

"""## Step 2 — NASA Earthdata Authentication

Create a free account at [urs.earthdata.nasa.gov](https://urs.earthdata.nasa.gov/) if you don't have one.
"""

import earthaccess
earthaccess.login(strategy="interactive")  # prompts for username / password

"""## Step 3 — Draw Your Area of Interest

Use the rectangle tool on the map below to define your search area.  
Run the **next cell** after drawing to confirm the bounding box.
"""

from ipyleaflet import Map, DrawControl, basemaps
from IPython.display import display

# Default center — adjust zoom/center as needed
m = Map(center=(39.5, -98.0), zoom=4, basemap=basemaps.OpenStreetMap.Mapnik)

draw_control = DrawControl(
    rectangle={"shapeOptions": {"color": "#e74c3c", "fillOpacity": 0.1}},
    polygon={}, polyline={}, circle={}, circlemarker={}, marker={}
)

bbox_coords = {}

def handle_draw(self, action, geo_json):
    global bbox_coords
    if geo_json['geometry']['type'] == 'Polygon':
        coords = geo_json['geometry']['coordinates'][0]
        lons = [c[0] for c in coords]
        lats = [c[1] for c in coords]
        bbox_coords = {
            "west":  min(lons), "east":  max(lons),
            "south": min(lats), "north": max(lats)
        }
        print(f"✅ Bounding box captured:")
        print(f"   West:  {bbox_coords['west']:.4f}")
        print(f"   East:  {bbox_coords['east']:.4f}")
        print(f"   South: {bbox_coords['south']:.4f}")
        print(f"   North: {bbox_coords['north']:.4f}")

draw_control.on_draw(handle_draw)
m.add_control(draw_control)
print("🗺️  Draw a rectangle on the map below, then run the next cell")
display(m)

# Confirm bounding box — falls back to continental US if nothing drawn
if not bbox_coords:
    print("⚠️  No box drawn — using default continental US bbox")
    bbox_coords = {"west": -125.0, "east": -66.9, "south": 24.4, "north": 49.4}

SEARCH_BBOX = (
    bbox_coords["west"],
    bbox_coords["south"],
    bbox_coords["east"],
    bbox_coords["north"]
)
print(f"📦 Search bounding box: {SEARCH_BBOX}")

"""## Step 4 — Select Date Range

Use the date pickers to define your temporal search window.  
EMIT data is available from **August 2022** onward.
"""

from ipywidgets import widgets
from IPython.display import display
import datetime

today          = datetime.date.today()
six_months_ago = today - datetime.timedelta(days=180)

start_picker = widgets.DatePicker(description="Start Date", value=six_months_ago)
end_picker   = widgets.DatePicker(description="End Date",   value=today)

print("📅 Select your date range:")
display(start_picker)
display(end_picker)

"""## Step 5 — Search EMIT L2B CH₄ Enhancement Granules (Pipeline B)

Searches NASA Earthdata for EMIT L2B CH4 Enhancement V002 granules
within your drawn area and selected date range.
"""

start_str = start_picker.value.strftime("%Y-%m-%dT00:00:00Z")
end_str   = end_picker.value.strftime("%Y-%m-%dT23:59:59Z")

print(f"🔍 Searching {start_str} → {end_str} ...")

results_ch4 = earthaccess.search_data(
    short_name="EMITL2BCH4ENH",
    version="002",
    bounding_box=SEARCH_BBOX,
    temporal=(start_str, end_str),
    count=50
)

print(f"\n✅ Found {len(results_ch4)} CH₄ granule(s)\n")
print(f"{'#':<5} {'Date':<12} {'Granule ID'}")
print("-" * 65)
for i, r in enumerate(results_ch4):
    name = r['umm']['GranuleUR']
    try:
        date_part = name.split("_")[3][:8]
        date_fmt  = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]}"
    except:
        date_fmt = "unknown"
    print(f"  [{i}]  {date_fmt}   {name}")

"""## Step 5b — Search EMIT L2A Reflectance Granules (Pipeline A)

Raw reflectance cubes are required for the Vegetation Stress pipeline.  
Try to match granule dates with the CH₄ results above.
"""

results_rfl = earthaccess.search_data(
    short_name="EMITL2ARFL",
    version="001",
    bounding_box=SEARCH_BBOX,
    temporal=(start_str, end_str),
    count=50
)

print(f"✅ Found {len(results_rfl)} L2A Reflectance granule(s)\n")
print(f"{'#':<5} {'Date':<12} {'Granule ID'}")
print("-" * 65)
for i, r in enumerate(results_rfl):
    name = r['umm']['GranuleUR']
    try:
        date_part = name.split("_")[3][:8]
        date_fmt  = f"{date_part[:4]}-{date_part[4:6]}-{date_part[6:8]}"
    except:
        date_fmt = "unknown"
    print(f"  [{i}]  {date_fmt}   {name}")

"""## Step 6 — Select & Download Granules

Pick matching granule indices from the lists above (same date = same orbit pass = co-registered data).
"""

from ipywidgets import widgets
from IPython.display import display

ch4_index = widgets.BoundedIntText(
    value=0, min=0, max=max(0, len(results_ch4)-1), step=1,
    description="CH₄ Granule #:"
)
rfl_index = widgets.BoundedIntText(
    value=0, min=0, max=max(0, len(results_rfl)-1), step=1,
    description="RFL Granule #:"
)

print("👆 Pick matching granule indices (same date recommended):")
display(ch4_index)
display(rfl_index)

import os
os.makedirs("emit_ch4", exist_ok=True)
os.makedirs("emit_rfl", exist_ok=True)

sel_ch4 = ch4_index.value
sel_rfl = rfl_index.value

print(f"📥 Downloading CH₄ granule [{sel_ch4}]...")
ch4_files = earthaccess.download(results_ch4[sel_ch4:sel_ch4+1], local_path="emit_ch4/")

print(f"\n📥 Downloading L2A RFL granule [{sel_rfl}]...")
rfl_files = earthaccess.download(results_rfl[sel_rfl:sel_rfl+1], local_path="emit_rfl/")

print("\n✅ Downloads complete:")
for f in ch4_files + rfl_files:
    print(f"  {f}")

"""## Step 7 — Inspect CH₄ GeoTIFF (Pipeline B)"""

import rasterio
import numpy as np

tif_files = [f for f in ch4_files if str(f).endswith(".tif")]
tif_path  = tif_files[0] if tif_files else None

if tif_path:
    with rasterio.open(tif_path) as src:
        print(f"📊 CH₄ File Info:")
        print(f"  Bands  : {src.count}")
        print(f"  Size   : {src.width} x {src.height}")
        print(f"  CRS    : {src.crs}")
        print(f"  Bounds : {src.bounds}")
        data = src.read(1)
        print(f"  Band 1 min/max: {data.min():.4f} / {data.max():.4f}")
else:
    print("⚠️  No .tif found — check emit_ch4/ folder for .nc files")

"""## Step 8 — Load L2A Reflectance Cube (Pipeline A)

EMIT L2A data is delivered as NetCDF4 (`.nc`).  
This cell loads it as a `(bands, rows, cols)` NumPy array.
"""

import netCDF4 as nc_lib
import numpy as np

nc_files = [f for f in rfl_files if str(f).endswith(".nc")]
nc_path  = nc_files[0] if nc_files else None

if nc_path:
    ds = nc_lib.Dataset(nc_path)
    print("📊 Root variables:", list(ds.variables.keys()))
    print("📁 Groups:", list(ds.groups.keys()))   # ← add this to inspect structure

    reflectance_data = ds.variables['reflectance'][:]
    reflectance_var  = ds.variables['reflectance']

    wl_emit = None

    # ✅ PRIMARY FIX: wavelengths live in the 'sensor_band_parameters' group
    if 'sensor_band_parameters' in ds.groups:
        sbp = ds.groups['sensor_band_parameters']
        if 'wavelengths' in sbp.variables:
            wl_emit = sbp.variables['wavelengths'][:]
            print("✅ Wavelengths found in group 'sensor_band_parameters'")

    # Fallback: root-level variables (older EMIT versions)
    if wl_emit is None and 'wavelengths' in ds.variables:
        wl_emit = ds.variables['wavelengths'][:]
    if wl_emit is None and 'wavelength' in ds.variables:
        wl_emit = ds.variables['wavelength'][:]

    # Fallback: scan ALL groups for wavelengths
    if wl_emit is None:
        for grp_name, grp in ds.groups.items():
            if 'wavelengths' in grp.variables:
                wl_emit = grp.variables['wavelengths'][:]
                print(f"✅ Wavelengths found in group '{grp_name}'")
                break

    if wl_emit is None:
        print("⚠️  Error: 'wavelengths' not found anywhere in the file.")
        cube = wl = None
        ds.close()
    else:
        cube = np.ma.filled(reflectance_data, fill_value=0).transpose(2, 0, 1).astype(np.float32)
        wl   = list(wl_emit)
        ds.close()
        print(f"\n✅ Cube shape : {cube.shape}  (bands, rows, cols)")
        print(f"   Wavelength range: {min(wl):.1f} – {max(wl):.1f} nm")
        print(f"   Total bands     : {len(wl)}")
else:
    print("⚠️  No .nc file found in emit_rfl/")

"""## Step 9 — Vegetation Stress Analysis (Pipeline A)

Computes a panel of Vegetation Indices (VIs) sensitive to underground CH₄-induced plant stress,
then combines them into a weighted stress score map.

> Based on: *Ma et al. (2024) Environ. Sci. Technol. 58(27), 12018–12027*
"""

# ── Vegetation Index functions (from ng_leak_detection.py by Ryan Kmetz) ──

def nearest_band(wavelengths, target_nm):
    arr = np.asarray(wavelengths)
    return int(np.argmin(np.abs(arr - target_nm)))

def compute_vegetation_indices(cube, wl):
    def band(nm):
        return cube[nearest_band(wl, nm)].astype(np.float64)
    eps = 1e-6
    R450=band(450); R500=band(500); R550=band(550); R570=band(570)
    R650=band(650); R670=band(670); R700=band(700); R720=band(720)
    R750=band(750); R800=band(800); R900=band(900)
    indices = {}
    indices["MCARI"]      = ((R700-R670) - 0.2*(R700-R550)) * (R700/(R670+eps))
    indices["NDVI"]       = (R800-R670) / (R800+R670+eps)
    indices["RENDVI"]     = (R750-R700) / (R750+R700+eps)
    indices["PRI"]        = (R550-R570) / (R550+R570+eps)
    indices["SIPI"]       = (R800-R450) / (R800-R670+eps)
    indices["WI"]         = R900 / (R570+eps)
    TCARI = 3*((R700-R670) - 0.2*(R700-R550)*(R700/(R670+eps)))
    OSAVI = (1+0.16)*(R800-R670)/(R800+R670+0.16)
    indices["TCARI_OSAVI"]= TCARI/(OSAVI+eps)
    return indices

def vi_stress_score(vi_dict):
    weights = {"MCARI":0.30,"NDVI":0.20,"RENDVI":0.15,
               "PRI":0.10,"SIPI":0.10,"WI":0.10,"TCARI_OSAVI":0.05}
    score   = np.zeros_like(next(iter(vi_dict.values())), dtype=np.float64)
    total_w = 0.0
    for name, w in weights.items():
        if name not in vi_dict: continue
        v = vi_dict[name].copy()
        vmin,vmax = np.nanpercentile(v,2), np.nanpercentile(v,98)
        if vmax-vmin < 1e-8: continue
        v_norm = np.clip((v-vmin)/(vmax-vmin),0,1)
        if name in ("MCARI","NDVI","RENDVI","PRI","WI"):
            v_norm = 1 - v_norm
        score   += w * v_norm
        total_w += w
    return score / (total_w + 1e-8)

print("🌿 Computing Vegetation Indices...")
vi_dict   = compute_vegetation_indices(cube, wl)
vi_stress = vi_stress_score(vi_dict)

print(f"   Computed: {', '.join(vi_dict.keys())}")
print(f"\n📊 Stress Stats:")
print(f"   Mean  : {vi_stress.mean():.3f}")
print(f"   Max   : {vi_stress.max():.3f}")
print(f"   High-stress pixels (>0.7): {(vi_stress > 0.7).sum()}")

"""## Step 10 — Visualize Vegetation Stress Maps"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

im0 = axes[0].imshow(vi_stress, cmap="RdYlGn_r", vmin=0, vmax=1)
plt.colorbar(im0, ax=axes[0], label="Stress Score")
axes[0].set_title("🌿 Vegetation Stress Score\n(Pipeline A — VI Composite)", fontsize=11)

mcari      = vi_dict["MCARI"]
mcari_disp = np.clip(mcari, np.nanpercentile(mcari,2), np.nanpercentile(mcari,98))
im1 = axes[1].imshow(mcari_disp, cmap="RdYlGn_r")
plt.colorbar(im1, ax=axes[1], label="MCARI")
axes[1].set_title("MCARI\n(Modified Chlorophyll Absorption Index)", fontsize=11)

ndvi = vi_dict["NDVI"]
im2  = axes[2].imshow(ndvi, cmap="RdYlGn", vmin=-0.1, vmax=0.9)
plt.colorbar(im2, ax=axes[2], label="NDVI")
axes[2].set_title("NDVI\n(Normalised Difference Vegetation Index)", fontsize=11)

plt.suptitle("Vegetation Stress Analysis — EMIT L2A Reflectance\n© Ryan Kmetz",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("veg_stress_map.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: veg_stress_map.png")

"""## Step 11 — Visualize CH₄ Enhancement Map (Pipeline B)"""

with rasterio.open(tif_path) as src:
    ch4     = src.read(1).astype(float)
    bounds  = src.bounds
    transform = src.transform

ch4 = np.where(ch4 < 0, np.nan, ch4)
threshold = np.nanpercentile(ch4, 95)
plume_mask = ch4 > threshold

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

im1 = axes[0].imshow(ch4, cmap="hot", aspect="auto")
axes[0].set_title("EMIT CH₄ Enhancement (ppm·m)", fontsize=13)
plt.colorbar(im1, ax=axes[0], label="ppm·m")

im2 = axes[1].imshow(ch4, cmap="gray", aspect="auto")
axes[1].imshow(np.where(plume_mask, ch4, np.nan), cmap="Reds", aspect="auto", alpha=0.8)
axes[1].set_title(f"Potential Plumes (top 5% > {threshold:.1f} ppm·m)", fontsize=13)
plt.colorbar(im2, ax=axes[1], label="ppm·m")

plt.suptitle("EMIT CH₄ Enhancement Map — Pipeline B\n© Ryan Kmetz",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("ch4_map.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: ch4_map.png")

"""## Step 12 — Detect CH₄ Plume Clusters (Pipeline B)

Labels connected regions of high CH₄ enhancement as candidate leak blobs.
"""

from scipy import ndimage
from skimage import measure

binary = np.nan_to_num(ch4) > threshold
labeled, num_features = ndimage.label(binary)
print(f"🔍 Found {num_features} potential leak cluster(s)\n")

regions = measure.regionprops(labeled, intensity_image=np.nan_to_num(ch4))

print(f"{'#':<5} {'Area (px)':<12} {'Max CH4 (ppm·m)':<20} {'Centroid (row, col)'}")
print("-" * 60)
for i, region in enumerate(regions):
    if region.area > 5:
        print(f"{i+1:<5} {region.area:<12} {region.max_intensity:<20.2f} "
              f"{str(tuple(int(x) for x in region.centroid))}")

"""## Step 13 — Convert Pixel Centroids to Lat/Lon"""

print(f"\n📍 Leak Locations (Lat/Lon):\n")
print(f"{'#':<5} {'Latitude':<15} {'Longitude':<15} {'Max CH4 (ppm·m)'}")
print("-" * 50)

leak_locations = []
for i, region in enumerate(regions):
    if region.area > 5:
        row, col = region.centroid
        lon, lat = rasterio.transform.xy(transform, row, col)
        print(f"{i+1:<5} {lat:<15.5f} {lon:<15.5f} {region.max_intensity:.2f}")
        leak_locations.append({
            "cluster": i+1, "lat": lat, "lon": lon,
            "area_px": region.area, "max_ch4_ppm_m": region.max_intensity
        })

"""## Step 14 — Fusion Score: Vegetation Stress + CH₄ Enhancement

Combines both pipelines into a single anomaly map.  
High fusion score = high confidence leak candidate.
"""

from skimage.transform import resize as sk_resize

vi_resized = sk_resize(vi_stress, ch4.shape, anti_aliasing=True)
ch4_norm   = (ch4 - np.nanmin(ch4)) / (np.nanmax(ch4) - np.nanmin(ch4) + 1e-8)
fusion     = 0.5 * vi_resized + 0.5 * np.nan_to_num(ch4_norm)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].imshow(vi_resized, cmap="RdYlGn_r", vmin=0, vmax=1)
axes[0].set_title("🌿 Veg Stress (Pipeline A)")

axes[1].imshow(np.nan_to_num(ch4_norm), cmap="hot")
axes[1].set_title("🛰️ CH₄ Enhancement (Pipeline B)")

im = axes[2].imshow(fusion, cmap="plasma")
plt.colorbar(im, ax=axes[2], label="Fusion Score")
axes[2].set_title("🔥 Fusion Score (A + B Combined)")

plt.suptitle("Combined Leak Detection — Vegetation Stress + SWIR CH₄\n© Ryan Kmetz",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.savefig("fusion_map.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Saved: fusion_map.png")

"""## Step 15 — Interactive Leak Map (Folium)

Plots confirmed CH₄ cluster centroids on an interactive map.
"""

import folium
import requests
import json

center_lat = (SEARCH_BBOX[1] + SEARCH_BBOX[3]) / 2
center_lon = (SEARCH_BBOX[0] + SEARCH_BBOX[2]) / 2

m = folium.Map(location=[center_lat, center_lon], zoom_start=7,
               tiles="CartoDB positron")

# ── EIA Natural Gas Pipelines (ArcGIS FeatureServer → GeoJSON) ─────────────
PIPELINE_FS = (
    "https://services2.arcgis.com/FiaPA4ga0iQKduv3/ArcGIS/rest/services"
    "/Natural_Gas_Interstate_and_Intrastate_Pipelines_1/FeatureServer/0/query"
)

# Spatial filter = your SEARCH_BBOX, pulled in chunks (FeatureServer max 2000 features)
bbox_geom = f"{SEARCH_BBOX[0]},{SEARCH_BBOX[1]},{SEARCH_BBOX[2]},{SEARCH_BBOX[3]}"

params = {
    "where": "1=1",
    "geometry": bbox_geom,
    "geometryType": "esriGeometryEnvelope",
    "inSR": "4326",
    "spatialRel": "esriSpatialRelIntersects",
    "outFields": "NAME,TYPEPIPE,OPERNAME,DIAMETER",
    "returnGeometry": True,
    "f": "geojson",
    "resultOffset": 0,
    "resultRecordCount": 2000
}

print("📡 Fetching NG pipeline features from EIA ArcGIS FeatureServer...")

try:
    resp = requests.get(PIPELINE_FS, params=params, timeout=30)
    resp.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)
    pipeline_geojson = resp.json()

    # Check if the response is an error object
    if "error" in pipeline_geojson:
        print(f"⚠️  ArcGIS FeatureServer Error: {pipeline_geojson['error'].get('message', 'Unknown error')}")
        feature_count = 0
        pipeline_geojson = {"type": "FeatureCollection", "features": []} # Provide empty GeoJSON
    else:
        feature_count = len(pipeline_geojson.get("features", []))
    print(f"✅ Fetched {feature_count} pipeline segment(s)")

except requests.exceptions.RequestException as e:
    print(f"❌ Failed to fetch pipeline data: {e}")
    feature_count = 0
    pipeline_geojson = {"type": "FeatureCollection", "features": []} # Provide empty GeoJSON

# ── Style function: Interstate = dark blue, Intrastate = steel blue ─────────
def pipeline_style(feature):
    ptype = (feature["properties"].get("TYPEPIPE") or "").upper()
    color = "#003580" if "INTER" in ptype else "#4682B4"
    return {
        "color": color,
        "weight": 2.5,
        "opacity": 0.85
    }

def pipeline_highlight(feature):
    return {"color": "#FFD700", "weight": 4.5, "opacity": 1.0}

pipeline_layer = folium.FeatureGroup(
    name="🔵 EIA Natural Gas Pipelines (Interstate + Intrastate)", show=True
)

# Only add GeoJson layer if features were successfully fetched
if feature_count > 0:
    folium.GeoJson(
        pipeline_geojson,
        name="EIA NG Pipelines",
        style_function=pipeline_style,
        highlight_function=pipeline_highlight,
        tooltip=folium.GeoJsonTooltip(
            fields=["NAME", "TYPEPIPE", "OPERNAME", "DIAMETER"],
            aliases=["Pipeline:", "Type:", "Operator:", "Diameter (in):"],
            localize=True,
            sticky=True
        )
    ).add_to(pipeline_layer)
else:
    print("ℹ️  No pipeline features to display or an error occurred during fetch.")

pipeline_layer.add_to(m)

# ── NPMS WMS Layer ───────────────────────────────────────────────────────────
folium.WmsTileLayer(
    url="https://pvnpms.phmsa.dot.gov/arcgis/services/NPMS/PublicViewer/MapServer/WmsServer",
    layers="0",
    name="🛢️ NPMS Gas Transmission (PHMSA)",
    fmt="image/png",
    transparent=True,
    overlay=True,
    control=True,
    show=False,   # secondary reference layer — off by default
    attr="PHMSA / DOT National Pipeline Mapping System"
).add_to(m)

# ── CH₄ Cluster Markers ──────────────────────────────────────────────────────
def marker_color(ch4_val):
    if ch4_val >= 6000:   return "#8B0000"
    elif ch4_val >= 4000: return "#FF0000"
    elif ch4_val >= 2500: return "#FF8C00"
    else:                 return "#FFD700"

leak_layer = folium.FeatureGroup(name="🔴 CH₄ Leak Candidates", show=True)

for loc in leak_locations:
    color = marker_color(loc["max_ch4_ppm_m"])
    folium.CircleMarker(
        location=[loc["lat"], loc["lon"]],
        radius=max(5, int(loc["area_px"] ** 0.5) * 2),
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.75,
        weight=1.5,
        popup=folium.Popup(
            f"""<b>Cluster {loc['cluster']}</b><br>
            Max CH₄: <b>{loc['max_ch4_ppm_m']:.0f} ppm·m</b><br>
            Area: {loc['area_px']} px ({loc['area_px'] * 3600:.0f} m²)<br>
            Lat: {loc['lat']:.5f}<br>
            Lon: {loc['lon']:.5f}""",
            max_width=220
        ),
        tooltip=f"CH₄: {loc['max_ch4_ppm_m']:.0f} ppm·m | {loc['area_px']} px"
    ).add_to(leak_layer)

leak_layer.add_to(m)

# ── Legend ───────────────────────────────────────────────────────────────────
legend_html = """
<div style="position:fixed; bottom:30px; left:30px; z-index:1000;
     background:white; padding:12px 16px; border-radius:8px;
     border:1px solid #ccc; font-size:13px; box-shadow:2px 2px 6px rgba(0,0,0,0.2)">
  <b>CH₄ Enhancement</b><br>
  <span style="color:#8B0000">●</span> &ge; 6,000 ppm·m — Critical<br>
  <span style="color:#FF0000">●</span> 4,000–5,999 ppm·m — High<br>
  <span style="color:#FF8C00">●</span> 2,500–3,999 ppm·m — Moderate<br>
  <span style="color:#FFD700">●</span> &lt; 2,500 ppm·m — Low<br>
  <hr style="margin:6px 0">
  <b>Pipelines</b><br>
  <span style="color:#003580">━</span> Interstate<br>
  <span style="color:#4682B4">━</span> Intrastate<br>
  <hr style="margin:6px 0">
  <span style="color:#555; font-size:11px">Circle size ∝ plume area</span>
</div>
"""
m.get_root().html.add_child(folium.Element(legend_html))

folium.LayerControl(collapsed=False).add_to(m)

m.save("leaks_map.html")
print("✅ Interactive map saved: leaks_map.html")
m

"""## Step 16 — Export Results to CSV"""

import csv

csv_path = "leak_detections.csv"
fieldnames = ["cluster", "lat", "lon", "area_px", "max_ch4_ppm_m"]

with open(csv_path, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(leak_locations)

print(f"✅ Exported {len(leak_locations)} detection(s) to {csv_path}")

"""---

## 📁 Output Files

| File | Description |
|------|-------------|
| `veg_stress_map.png` | Vegetation stress VI maps (Pipeline A) |
| `ch4_map.png` | CH₄ enhancement heatmap (Pipeline B) |
| `fusion_map.png` | Combined fusion score map |
| `leaks_map.html` | Interactive Folium map |
| `leak_detections.csv` | Tabular results with lat/lon |

---

**© 2025 Ryan Kmetz** — MIT License  
Data: NASA EMIT via [NASA Earthdata](https://earthdata.nasa.gov/)  
References:  
- Ma et al. (2024) *Environ. Sci. Technol.* 58(27), 12018–12027. DOI: 10.1021/acs.est.4c03345  
- DigitalSense AI (2025) *Introduction to Methane Detection: Satellites & Techniques*

"""
