# -*- coding: utf-8 -*-
"""nyc_heat_ems_uhi_landsat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qXKgiIHsTAlATRv8U-EQfqJcB4jp1ZIu

# NYC Extreme Heat Distress + Urban Heat Island Analysis
## UHI via Landsat LST (NASA ARSET methodology) · Microsoft Planetary Computer

**Workflow (follows NASA ARSET "Satellite Remote Sensing for Measuring Urban Heat Islands" training):**

1. Pull 311 heat-related distress calls (2022–2024 summers) from NYC Open Data
2. **Fetch Landsat 8/9 Collection 2 Level-2 scenes** from Microsoft Planetary Computer (free, no auth required)
   - Band: `lwir11` (Band 10, Thermal Infrared)
   - Filter: summers (June–Sept), cloud cover < 20%, 2022–2024
   - Convert DN → Kelvin → Fahrenheit using USGS scale/offset
   - Compute mean summer LST composite across scenes
   - Z-score → UHI intensity raster
3. Load FDNY + EMS stations from NYC Open Data
4. Load NYC Heat Vulnerability Index (HVI) from NYC Open Data
5. Spatial join: count distress calls within 500 ft buffer of each station
6. Extract LST z-score at each station via nearest-pixel sample
7. Anomaly detection + map + summary table

> **No GEE, no NASA EarthData login, no Docker.** Planetary Computer provides anonymous access via SAS tokens auto-handled by the `planetary-computer` SDK.
"""

!pip install geopandas folium mapclassify requests shapely \
             pystac-client planetary-computer odc-stac \
             xarray rioxarray rasterio numpy matplotlib -q

import requests
import pandas as pd
import geopandas as gpd
import numpy as np
import xarray as xr
import rioxarray
import rasterio
from rasterio.transform import from_bounds
from shapely.geometry import Point, box, mapping
import folium
from folium.plugins import HeatMap
import matplotlib.pyplot as plt
import warnings
import io, json, time
warnings.filterwarnings('ignore')

import pystac_client
import planetary_computer
import odc.stac

print('Libraries loaded.')
print(f'pystac-client version: {pystac_client.__version__}')

"""## 1. Pull 311 Heat Distress Calls (Summers 2022–2024)

Filters for building-level and street-level heat burden indicators during June–September.
"""

print('Fetching 311 heat distress calls (summers 2022-2024)...')

url_311 = 'https://data.cityofnewyork.us/resource/erm2-nwe9.json'

HEAT_WHERE = (
    "(complaint_type = 'HEAT/HOT WATER' "
    " OR complaint_type = 'Unsanitary Condition' "
    " OR descriptor LIKE '%Heat%' OR descriptor LIKE '%heat%' "
    " OR descriptor LIKE '%Hot%' OR descriptor LIKE '%hot%') "
    "AND created_date >= '2022-06-01T00:00:00' "
    "AND created_date <= '2024-09-30T23:59:59' "
    "AND latitude IS NOT NULL"
)

params_311 = {
    '$where': HEAT_WHERE,
    '$limit': 100000,
    '$select': 'unique_key, created_date, complaint_type, descriptor, latitude, longitude, borough'
}

resp = requests.get(url_311, params=params_311, timeout=120)
resp.raise_for_status()
df_311 = pd.DataFrame(resp.json())

df_311['latitude']     = pd.to_numeric(df_311['latitude'],  errors='coerce')
df_311['longitude']    = pd.to_numeric(df_311['longitude'], errors='coerce')
df_311['created_date'] = pd.to_datetime(df_311['created_date'])
df_311 = df_311.dropna(subset=['latitude', 'longitude'])
df_311 = df_311[df_311['created_date'].dt.month.isin([6, 7, 8, 9])]

gdf_311 = gpd.GeoDataFrame(
    df_311,
    geometry=gpd.points_from_xy(df_311.longitude, df_311.latitude),
    crs='EPSG:4326'
)

print(f'  Summer heat distress calls: {len(gdf_311):,}')
print(f'  Date range: {df_311["created_date"].min().date()} → {df_311["created_date"].max().date()}')

"""## 2. Land Surface Temperature via Planetary Computer (ARSET Methodology)

### Background
Following the NASA ARSET UHI training, we use **Landsat Collection 2 Level-2** thermal data:
- **Band:** `lwir11` (Band 10 on L8/L9) — Long-wave infrared, 100m resampled to 30m
- **Product:** Surface temperature, already atmospherically corrected by USGS
- **Conversion:** `LST_Kelvin = DN × 0.00341802 + 149.0` (USGS Collection 2 scale/offset)
- **Collection:** `landsat-c2-l2` on Planetary Computer (Landsat 4–9 unified)

### Access
Planetary Computer uses **Azure SAS tokens** for data access — the `planetary-computer` SDK handles this automatically. No account needed for anonymous access; an optional free API key lifts rate limits.

### Scene selection
- Summers 2022–2024 (June 1 – September 30 each year)
- Cloud cover < 20%
- Landsat 8 or 9 (OLI-TIRS sensor)
- NYC bounding box
- We stack all qualifying scenes and take the **mean** to get a stable summer LST composite
"""

# NYC bounding box (WGS84)
NYC_BBOX = [-74.26, 40.49, -73.69, 40.93]  # [west, south, east, north]

# Connect to Planetary Computer STAC API (anonymous, no key needed)
catalog = pystac_client.Client.open(
    'https://planetarycomputer.microsoft.com/api/stac/v1',
    modifier=planetary_computer.sign_inplace  # auto-signs asset URLs with SAS tokens
)
print('Connected to Planetary Computer STAC API')

# Search for Landsat C2 L2 scenes over NYC for 3 summers
# We search each year separately then combine to ensure even seasonal coverage
all_items = []
for year in [2022, 2023, 2024]:
    search = catalog.search(
        collections=['landsat-c2-l2'],
        bbox=NYC_BBOX,
        datetime=f'{year}-06-01/{year}-09-30',
        query={
            'eo:cloud_cover': {'lt': 20},
            'platform': {'in': ['landsat-8', 'landsat-9']}
        }
    )
    items = list(search.items())
    print(f'  {year}: {len(items)} scenes (cloud < 20%, L8/L9)')
    all_items.extend(items)

print(f'\nTotal scenes: {len(all_items)}')

# Preview metadata of first scene
if all_items:
    sample = all_items[0]
    print(f'\nSample scene: {sample.id}')
    print(f'  Date: {sample.datetime}')
    print(f'  Platform: {sample.properties.get("platform")}')
    print(f'  Cloud cover: {sample.properties.get("eo:cloud_cover")}%')
    print(f'  Available bands: {list(sample.assets.keys())[:15]}')

# Load the lwir11 (thermal) band for all scenes into an xarray DataArray
# odc.stac.load handles the SAS token signing, COG streaming, and reprojection

print('Loading lwir11 (thermal infrared) band from Planetary Computer...')
print('(Streaming COGs from Azure Blob Storage — may take 2-5 minutes for 3 summers of scenes)')

# Use UTM 18N (EPSG:32618) — appropriate projection for NYC at 30m
# odc-stac will reproject all scenes to this CRS on-the-fly
ds_lst = odc.stac.load(
    all_items,
    bbox=NYC_BBOX,
    bands=['lwir11'],
    crs='EPSG:32618',
    resolution=30,
    groupby='solar_day',    # one composite per unique overpass date
    chunks={'time': 1, 'x': 512, 'y': 512}  # lazy-load with dask chunks
)

print(f'Dataset loaded: {ds_lst}')
print(f'\nDimensions: {dict(ds_lst.dims)}')
print(f'Time steps (unique overpasses): {len(ds_lst.time)}')

# ── ARSET LST Conversion ──
# Landsat C2 L2 surface temperature is stored as scaled integers.
# USGS scale: LST (Kelvin) = DN × 0.00341802 + 149.0
# Reference: USGS Landsat Collection 2 Level-2 Science Product Guide

SCALE  = 0.00341802
OFFSET = 149.0

print('Converting DN → Kelvin → Fahrenheit...')

lwir = ds_lst['lwir11'].astype('float32')

# Mask fill/nodata values (0 and 65535 are common fill values in C2 L2)
lwir = lwir.where((lwir > 0) & (lwir < 65535))

# DN → Kelvin
lst_k = lwir * SCALE + OFFSET

# Kelvin → Fahrenheit  (ARSET training uses Fahrenheit for US audiences)
lst_f = (lst_k - 273.15) * 9/5 + 32

# Sanity check: NYC summer LST should be roughly 60°F–130°F
lst_f_computed = lst_f.compute()  # trigger dask computation
print(f'  LST range: {float(lst_f_computed.min()):.1f}°F – {float(lst_f_computed.max()):.1f}°F')
print(f'  Mean LST: {float(lst_f_computed.mean()):.1f}°F')
print(f'  Scenes with valid data: {int((~np.isnan(lst_f_computed)).any(dim=["x","y"]).sum())}')

# ── Build mean summer LST composite ──
# Mean across all overpasses = stable seasonal signal
# This is the ARSET approach: temporal composite to reduce cloud/noise artifacts

print('Building mean summer LST composite across all overpasses...')
lst_mean = lst_f_computed.mean(dim='time', skipna=True)

print(f'  Composite LST range: {float(lst_mean.min()):.1f}°F – {float(lst_mean.max()):.1f}°F')
print(f'  Composite LST mean:  {float(lst_mean.mean()):.1f}°F')
print(f'  Output shape: {lst_mean.shape} (y × x pixels at 30m resolution)')

# ── Z-score the composite to get UHI intensity ──
# Z-score tells us how many standard deviations above/below city-wide mean each pixel is
# Positive z = warmer = UHI hotspot; Negative z = cooler = park/water/green space
lst_global_mean = float(lst_mean.mean())
lst_global_std  = float(lst_mean.std())

lst_zscore = (lst_mean - lst_global_mean) / lst_global_std

print(f'\nUHI z-score range: {float(lst_zscore.min()):.2f} – {float(lst_zscore.max()):.2f}')
print(f'  Global mean LST: {lst_global_mean:.1f}°F')
print(f'  Global std LST:  {lst_global_std:.1f}°F')

# ── Quick diagnostic plot ──
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

lst_mean.plot(
    ax=axes[0],
    cmap='inferno',
    robust=True,
    cbar_kwargs={'label': 'LST (°F)'}
)
axes[0].set_title('Mean Summer LST (Landsat C2 L2, 2022–2024)')
axes[0].set_aspect('equal')

lst_zscore.plot(
    ax=axes[1],
    cmap='RdBu_r',
    robust=True,
    vmin=-3, vmax=3,
    cbar_kwargs={'label': 'UHI z-score'}
)
axes[1].set_title('UHI Intensity (z-score, warmer = redder)')
axes[1].set_aspect('equal')

plt.tight_layout()
plt.savefig('nyc_lst_composite.png', dpi=120, bbox_inches='tight')
plt.show()
print('Saved nyc_lst_composite.png')

# ── Export composite raster to GeoTIFF for use in the rest of the analysis ──
# This lets us do point sampling (station UHI extraction) using rasterio

import os

LST_MEAN_TIF  = 'nyc_lst_mean_f.tif'
LST_ZSCORE_TIF = 'nyc_lst_zscore.tif'

def save_raster_to_tif(da, filepath, crs_epsg=32618):
    """Save an xarray DataArray to GeoTIFF using rioxarray."""
    da_out = da.copy()
    # Ensure spatial_ref / CRS is attached
    if not da_out.rio.crs:
        da_out = da_out.rio.write_crs(f'EPSG:{crs_epsg}')
    da_out = da_out.rio.write_nodata(np.nan)
    da_out.rio.to_raster(filepath, driver='GTiff', dtype='float32')
    print(f'  Saved {filepath} ({os.path.getsize(filepath)/1e6:.1f} MB)')

print('Saving rasters...')
save_raster_to_tif(lst_mean,   LST_MEAN_TIF)
save_raster_to_tif(lst_zscore, LST_ZSCORE_TIF)

"""## 3. Load FDNY Firehouses + EMS Stations"""

def parse_station_gdf(df, source_label):
    lat_col = next((c for c in df.columns if 'lat' in c.lower()), None)
    lon_col = next((c for c in df.columns if 'lon' in c.lower() or 'lng' in c.lower()), None)
    if lat_col is None and 'the_geom' in df.columns:
        df['longitude'] = df['the_geom'].apply(lambda g: g['coordinates'][0] if isinstance(g, dict) else None)
        df['latitude']  = df['the_geom'].apply(lambda g: g['coordinates'][1] if isinstance(g, dict) else None)
        lat_col, lon_col = 'latitude', 'longitude'
    elif lat_col is None and 'location' in df.columns:
        df['latitude']  = df['location'].apply(lambda x: float(x['latitude'])  if isinstance(x, dict) else None)
        df['longitude'] = df['location'].apply(lambda x: float(x['longitude']) if isinstance(x, dict) else None)
        lat_col, lon_col = 'latitude', 'longitude'
    df[lat_col] = pd.to_numeric(df[lat_col], errors='coerce')
    df[lon_col] = pd.to_numeric(df[lon_col], errors='coerce')
    df = df.dropna(subset=[lat_col, lon_col])
    name_col = next((c for c in df.columns if any(k in c.lower() for k in ['name','facilityname','facname','unit_id'])), None)
    df['station_name'] = df[name_col].astype(str) if name_col else f'{source_label} Station'
    df['source'] = source_label
    return gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df[lon_col], df[lat_col]), crs='EPSG:4326')

print('Fetching FDNY firehouses...')
df_fire = pd.DataFrame(requests.get('https://data.cityofnewyork.us/resource/hc8x-tcnd.json', params={'$limit': 500}).json())
gdf_fire = parse_station_gdf(df_fire.copy(), 'FDNY')
print(f'  FDNY: {len(gdf_fire)}')

print('Fetching EMS stations...')
df_ems_raw = pd.DataFrame(requests.get('https://data.cityofnewyork.us/resource/9ekd-5pvv.json', params={'$limit': 500}).json())
if len(df_ems_raw) < 5:
    df_ems_raw = pd.DataFrame(requests.get(
        'https://data.cityofnewyork.us/resource/ji82-xba5.json',
        params={'$where': "factype LIKE '%EMS%' OR facgroup LIKE '%Emergency%'", '$limit': 500}
    ).json())

if len(df_ems_raw) > 0:
    gdf_ems = parse_station_gdf(df_ems_raw.copy(), 'EMS')
    gdf_stations = pd.concat([gdf_fire, gdf_ems], ignore_index=True)
else:
    gdf_stations = gdf_fire.copy()

print(f'Total stations: {len(gdf_stations)}')
print(gdf_stations['source'].value_counts().to_string())

"""## 4. Load NYC Heat Vulnerability Index (HVI)"""

print('Loading NYC Heat Vulnerability Index...')
# Corrected URL for NYC Heat Vulnerability Index (HVI) by NTA
df_hvi = pd.DataFrame(requests.get('https://data.cityofnewyork.us/resource/q3b3-ypj4.json', params={'$limit': 500}).json())
print(f'  HVI records: {len(df_hvi)} | Columns: {df_hvi.columns.tolist()}')

print('Loading NTA boundaries...')
gdf_nta = None
for url in [
    'https://data.cityofnewyork.us/api/geospatial/9nt8-h7nd?method=export&format=geojson',
    'https://data.cityofnewyork.us/api/geospatial/cpf4-rkhq?method=export&format=geojson',
]:
    try:
        r = requests.get(url, timeout=60)
        gdf_nta = gpd.read_file(io.StringIO(r.text)).to_crs('EPSG:4326')
        print(f'  NTA loaded: {len(gdf_nta)} features | Columns: {gdf_nta.columns.tolist()}')
        break
    except Exception as e:
        print(f'  Failed: {e}')

# Join HVI to NTA polygons
# Adjusting column name lookups for the new HVI dataset (q3b3-ypj4)
hvi_ntacode_col = next((c for c in df_hvi.columns if c.lower() == 'nta_code'), None)
nta_ntacode_col = next((c for c in gdf_nta.columns if 'ntacode' in c.lower() or 'nta_code' in c.lower()), None) if gdf_nta is not None else None
hvi_score_col   = next((c for c in df_hvi.columns if c.lower() == 'hvi_score_2018'), None) # Specific column name for 2018 HVI score

print(f'  HVI join: "{hvi_ntacode_col}" → "{nta_ntacode_col}" | Score column: "{hvi_score_col}"')

if all([gdf_nta is not None, hvi_ntacode_col, nta_ntacode_col, hvi_score_col]):
    df_hvi[hvi_score_col] = pd.to_numeric(df_hvi[hvi_score_col], errors='coerce')
    df_join = df_hvi[[hvi_ntacode_col, hvi_score_col]].rename(columns={hvi_ntacode_col: '_key', hvi_score_col: 'hvi_score'})
    gdf_nta['_key'] = gdf_nta[nta_ntacode_col].astype(str).str.strip()
    df_join['_key'] = df_join['_key'].astype(str).str.strip()
    gdf_nta = gdf_nta.merge(df_join, on='_key', how='left')
    print(f'  HVI matched: {gdf_nta["hvi_score"].notna().sum()}/{len(gdf_nta)} NTAs')
else:
    # Fallback to uniform HVI if data loading or joining fails
    if gdf_nta is not None:
        gdf_nta['hvi_score'] = 3
        print('  Fallback: uniform HVI=3 due to data loading/join issues.')
    else:
        print('  Fallback not possible: NTA boundaries could not be loaded.')

"""## 5. Spatial Analysis: Buffer Stations → Count Heat Calls → Join HVI + Landsat LST

The key upgrade over the OpenMeteo version: instead of a coarse 3.5 km air-temp grid, each station now gets its LST z-score sampled from the 30m Landsat composite raster — the same pixel-level resolution used in the ARSET training exercises.
"""

LOCAL_CRS   = 'EPSG:2263'  # NY State Plane (feet)
LANDSAT_CRS = 'EPSG:32618' # UTM 18N — CRS of the Landsat raster
BUFFER_FEET = 500

gdf_311_proj      = gdf_311.to_crs(LOCAL_CRS)
gdf_stations_proj = gdf_stations.to_crs(LOCAL_CRS)
gdf_nta_proj      = gdf_nta.to_crs(LOCAL_CRS) if gdf_nta is not None and len(gdf_nta) > 0 else None

print(f'Reprojected layers to {LOCAL_CRS}')

# Buffer + spatial join 311 calls
gdf_stations_proj['buffer_geom'] = gdf_stations_proj.geometry.buffer(BUFFER_FEET)
gdf_buf = gpd.GeoDataFrame(
    gdf_stations_proj[['station_name', 'source', 'buffer_geom']].copy(),
    geometry='buffer_geom', crs=LOCAL_CRS
)

joined = gpd.sjoin(gdf_311_proj[['geometry']].copy(), gdf_buf, how='inner', predicate='within')
counts = joined.groupby('station_name').size().to_dict()
gdf_stations_proj['heat_calls'] = gdf_stations_proj['station_name'].map(counts).fillna(0).astype(int)
gdf_stations_proj = gdf_stations_proj.drop(columns=['buffer_geom'])

print(f'\nTop 10 stations by heat distress calls:')
print(
    gdf_stations_proj[['station_name','source','heat_calls']]
    .sort_values('heat_calls', ascending=False).head(10).to_string(index=False)
)

# ── Sample Landsat LST z-score at each station (30m pixel) ──
# Reproject stations to UTM 18N to match the raster, then sample nearest pixel

print('Sampling Landsat LST z-score at each station...')

gdf_stations_utm = gdf_stations_proj.to_crs(LANDSAT_CRS)

# Open the saved GeoTIFF with rasterio for point sampling
lst_zscores_sampled = []
lst_means_sampled   = []

with rasterio.open(LST_ZSCORE_TIF) as src_z, rasterio.open(LST_MEAN_TIF) as src_m:
    for _, row in gdf_stations_utm.iterrows():
        x, y = row.geometry.x, row.geometry.y
        # Sample single pixel at station location
        try:
            z_val = list(src_z.sample([(x, y)]))[0][0]
            m_val = list(src_m.sample([(x, y)]))[0][0]
            lst_zscores_sampled.append(float(z_val) if not np.isnan(z_val) else None)
            lst_means_sampled.append(float(m_val) if not np.isnan(m_val) else None)
        except Exception:
            lst_zscores_sampled.append(None)
            lst_means_sampled.append(None)

gdf_stations_proj['lst_zscore']  = lst_zscores_sampled
gdf_stations_proj['lst_mean_f']  = lst_means_sampled

valid = gdf_stations_proj['lst_zscore'].notna().sum()
print(f'  Stations with valid LST sample: {valid}/{len(gdf_stations_proj)}')
print(f'  LST z-score range: {gdf_stations_proj["lst_zscore"].min():.2f} – {gdf_stations_proj["lst_zscore"].max():.2f}')
print(f'  LST mean°F range: {gdf_stations_proj["lst_mean_f"].min():.1f}°F – {gdf_stations_proj["lst_mean_f"].max():.1f}°F')

# ── Join NTA HVI score to each station ──
if gdf_nta_proj is not None and 'hvi_score' in gdf_nta_proj.columns:
    station_hvi = gpd.sjoin(
        gdf_stations_proj[['station_name','heat_calls','source','geometry']].copy(),
        gdf_nta_proj[['hvi_score','geometry']].copy(),
        how='left', predicate='within'
    ).sort_values('hvi_score', ascending=False).drop_duplicates('station_name')
    gdf_stations_proj = gdf_stations_proj.merge(
        station_hvi[['station_name','hvi_score']], on='station_name', how='left'
    )
    gdf_stations_proj['nta_hvi'] = pd.to_numeric(gdf_stations_proj['hvi_score'], errors='coerce').fillna(3)
else:
    gdf_stations_proj['nta_hvi'] = 3

print('Station summary (top 10 by heat calls):')
print(
    gdf_stations_proj[['station_name','source','heat_calls','nta_hvi','lst_zscore','lst_mean_f']]
    .sort_values('heat_calls', ascending=False).head(10).to_string(index=False)
)

"""## 6. Anomaly Detection

**Anomaly:** station in a *low/moderate HVI neighborhood* (HVI ≤ 3) with *above-median heat call volume*.

We now have a 30m Landsat LST z-score for each station, so we can cross-check: are anomaly stations also in a Landsat-identified UHI hotspot (lst_zscore > 0.5)? That's the triple-convergence signal — community calling, index misses it, but the satellite sees the heat.
"""

median_calls      = gdf_stations_proj['heat_calls'].median()
HIGH_HVI          = 4
LST_HOT_THRESHOLD = 0.5  # z > 0.5 = meaningfully warmer than city average

gdf_anomalies = gdf_stations_proj[
    (gdf_stations_proj['nta_hvi'] < HIGH_HVI) &
    (gdf_stations_proj['heat_calls'] > median_calls)
].copy()

gdf_hotspots = gdf_stations_proj[
    (gdf_stations_proj['nta_hvi'] >= HIGH_HVI) &
    (gdf_stations_proj['heat_calls'] > median_calls)
].copy()

# Triple-convergence: anomaly + Landsat confirms hot
gdf_triple = gdf_anomalies[
    gdf_anomalies['lst_zscore'].fillna(0) > LST_HOT_THRESHOLD
].copy()

print(f'Median heat calls: {median_calls:.0f}')
print(f'Anomaly stations (low/mod HVI, high calls):  {len(gdf_anomalies)}')
print(f'Hotspot stations (high HVI + high calls):    {len(gdf_hotspots)}')
print(f'Triple-convergence (anomaly + Landsat hot):  {len(gdf_triple)}')

print('\nTriple-convergence stations (the most compelling anomalies):')
print(
    gdf_triple[['station_name','source','heat_calls','nta_hvi','lst_zscore','lst_mean_f']]
    .sort_values('lst_zscore', ascending=False).to_string(index=False)
)

print('\nAll anomaly stations:')
print(
    gdf_anomalies[['station_name','source','heat_calls','nta_hvi','lst_zscore','lst_mean_f']]
    .sort_values('heat_calls', ascending=False).head(15).to_string(index=False)
)

"""## 7. Map"""

gdf_stations_wgs  = gdf_stations_proj.to_crs('EPSG:4326')
gdf_anomalies_wgs = gdf_anomalies.to_crs('EPSG:4326')
gdf_hotspots_wgs  = gdf_hotspots.to_crs('EPSG:4326')
gdf_triple_wgs    = gdf_triple.to_crs('EPSG:4326')
gdf_nta_wgs       = gdf_nta.to_crs('EPSG:4326') if gdf_nta is not None else None

m = folium.Map(location=[40.72, -73.97], zoom_start=11, tiles='CartoDB dark_matter')

# ── HVI polygons ──
if gdf_nta_wgs is not None and 'hvi_score' in gdf_nta_wgs.columns:
    hvi_valid = gdf_nta_wgs.dropna(subset=['hvi_score']).copy()
    palette = {1:'#2166ac',2:'#74add1',3:'#fee090',4:'#f46d43',5:'#d73027'}
    folium.GeoJson(
        json.loads(hvi_valid.to_json()),
        name='Heat Vulnerability Index (HVI)',
        style_function=lambda x: {
            'fillColor': palette.get(int(x['properties'].get('hvi_score',3)),'#888'),
            'color':'#444','weight':0.4,'fillOpacity':0.35
        },
        tooltip=folium.GeoJsonTooltip(fields=['hvi_score'], aliases=['HVI:'])
    ).add_to(m)

# ── 311 heatmap ──
HeatMap(
    [[r.latitude, r.longitude] for _, r in gdf_311.iterrows()],
    name='311 Heat Calls (heatmap)',
    radius=9, blur=14, min_opacity=0.25,
    gradient={0.2:'blue',0.5:'yellow',1.0:'red'}
).add_to(m)

# ── All stations ──
all_grp = folium.FeatureGroup(name='All Stations')
for _, row in gdf_stations_wgs.iterrows():
    color = '#6baed6' if row['source']=='EMS' else '#aaaaaa'
    lst_z = row.get('lst_zscore') or 0
    lst_f = row.get('lst_mean_f') or 0
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=5, color=color, fill=True, fill_color=color, fill_opacity=0.5,
        tooltip=f"{row['source']}: {row['station_name']} | {int(row['heat_calls'])} calls | HVI {row.get('nta_hvi','?')} | LST {lst_f:.0f}°F (z={lst_z:.2f})"
    ).add_to(all_grp)
all_grp.add_to(m)

# ── Expected hotspots (orange) ──
hot_grp = folium.FeatureGroup(name='Expected Hotspots (high HVI + high calls)')
for _, row in gdf_hotspots_wgs.iterrows():
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=9, color='#fff', weight=2, fill=True, fill_color='#f46d43', fill_opacity=0.9,
        tooltip=f"HOTSPOT: {row['station_name']} | {int(row['heat_calls'])} calls | HVI {row.get('nta_hvi','?')}"
    ).add_to(hot_grp)
hot_grp.add_to(m)

# ── Anomalies (yellow) ──
anom_grp = folium.FeatureGroup(name='ANOMALY: Low HVI, High Calls')
for _, row in gdf_anomalies_wgs.iterrows():
    lst_z = row.get('lst_zscore') or 0
    lst_f = row.get('lst_mean_f') or 0
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=11, color='#fff', weight=2.5, fill=True, fill_color='#ffe000', fill_opacity=0.95,
        tooltip=f"ANOMALY: {row['station_name']} | {int(row['heat_calls'])} calls | HVI {row.get('nta_hvi','?')} (LOW) | LST {lst_f:.0f}°F z={lst_z:.2f}"
    ).add_to(anom_grp)
anom_grp.add_to(m)

# ── Triple-convergence (bright magenta) ──
triple_grp = folium.FeatureGroup(name='TRIPLE: Anomaly + Landsat Hot')
for _, row in gdf_triple_wgs.iterrows():
    lst_z = row.get('lst_zscore') or 0
    lst_f = row.get('lst_mean_f') or 0
    folium.CircleMarker(
        location=[row.geometry.y, row.geometry.x],
        radius=13, color='#fff', weight=3, fill=True, fill_color='#ff00cc', fill_opacity=0.95,
        tooltip=f"TRIPLE 🔴: {row['station_name']} | {int(row['heat_calls'])} calls | HVI {row.get('nta_hvi','?')} | LST {lst_f:.0f}°F z={lst_z:.2f}"
    ).add_to(triple_grp)
    folium.Marker(
        location=[row.geometry.y, row.geometry.x],
        icon=folium.DivIcon(
            html='<div style="font-size:14px;margin-top:-24px;margin-left:12px;">🔴</div>',
            icon_size=(20,20), icon_anchor=(0,0)
        )
    ).add_to(triple_grp)
triple_grp.add_to(m)

folium.LayerControl(collapsed=False).add_to(m)
m.save('nyc_heat_distress_landsat_uhi.html')
print('Map saved → nyc_heat_distress_landsat_uhi.html')
m

"""## 8. Summary Table"""

from IPython.display import HTML

summary = gdf_stations_proj[['station_name','source','heat_calls','nta_hvi','lst_zscore','lst_mean_f']]\
    .sort_values('heat_calls', ascending=False).reset_index(drop=True)

max_calls = summary['heat_calls'].max()
rows_html = ''
for _, row in summary.iterrows():
    calls   = int(row['heat_calls'])
    hvi     = float(row.get('nta_hvi', 3) or 3)
    lst_z   = float(row.get('lst_zscore') or 0)
    lst_f   = float(row.get('lst_mean_f') or 0)
    bar_pct = int(calls / max_calls * 100) if max_calls > 0 else 0

    is_anomaly = (hvi < HIGH_HVI) and (calls > median_calls)
    is_hotspot = (hvi >= HIGH_HVI) and (calls > median_calls)
    is_triple  = is_anomaly and (lst_z > LST_HOT_THRESHOLD)

    dot_color = '#ff00cc' if is_triple else ('#ffe000' if is_anomaly else ('#f46d43' if is_hotspot else '#aaaaaa'))
    flag = ' 🔴' if is_triple else (' ⚠️' if is_anomaly else '')

    if hvi >= 4:  hvi_badge = '<span style="background:#f46d4322;color:#b83012;padding:2px 8px;border-radius:4px;font-size:11px;">High HVI</span>'
    elif hvi >= 3: hvi_badge = '<span style="background:#fee09022;color:#8a6800;padding:2px 8px;border-radius:4px;font-size:11px;">Moderate HVI</span>'
    else:          hvi_badge = '<span style="background:#2166ac22;color:#0d4a8a;padding:2px 8px;border-radius:4px;font-size:11px;">Low HVI</span>'

    lst_badge_color = '#cc0000' if lst_z > 1 else ('#ff8800' if lst_z > 0.5 else ('#888' if lst_z < -0.5 else '#333'))

    rows_html += f'''
    <tr style="border-bottom:0.5px solid #e8e8e8;">
      <td style="padding:7px 10px;">
        <span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:{dot_color};margin-right:6px;"></span>
        {row["station_name"]}{flag}</td>
      <td style="padding:7px 10px;font-size:11px;color:#666;">{row["source"]}</td>
      <td style="padding:7px 10px;">
        <div style="background:#eee;border-radius:3px;height:7px;width:100%;max-width:180px;">
          <div style="background:{dot_color};width:{bar_pct}%;height:7px;border-radius:3px;"></div>
        </div></td>
      <td style="padding:7px 10px;text-align:right;">{calls:,}</td>
      <td style="padding:7px 10px;">{hvi_badge}</td>
      <td style="padding:7px 10px;text-align:right;font-size:12px;color:{lst_badge_color};font-weight:500;">{lst_f:.0f}°F</td>
      <td style="padding:7px 10px;text-align:right;font-size:11px;color:{lst_badge_color};">{lst_z:+.2f}</td>
    </tr>'''

html = f'''
<style>.ht{{width:100%;border-collapse:collapse;font-family:sans-serif;font-size:13px;}}
.ht tr:hover td{{background:#f9f9f9;}}</style>
<h3 style="font-family:sans-serif;font-size:15px;margin:16px 0 6px;">NYC Heat Distress + Landsat UHI · Station Summary</h3>
<div style="font-family:sans-serif;font-size:12px;margin-bottom:10px;color:#555;">
  🔴 Triple convergence: low HVI + high calls + Landsat hot |
  ⚠️ Anomaly: low HVI + high calls |
  🟠 Expected hotspot: high HVI + high calls
</div>
<table class="ht">
  <thead><tr style="border-bottom:2px solid #ccc;">
    <th style="padding:8px 10px;text-align:left;font-size:12px;color:#666;font-weight:500;">Station</th>
    <th style="padding:8px 10px;text-align:left;font-size:12px;color:#666;font-weight:500;">Type</th>
    <th style="padding:8px 10px;font-size:12px;color:#666;font-weight:500;">311 Heat Calls</th>
    <th style="padding:8px 10px;text-align:right;font-size:12px;color:#666;font-weight:500;">Count</th>
    <th style="padding:8px 10px;font-size:12px;color:#666;font-weight:500;">HVI Zone</th>
    <th style="padding:8px 10px;text-align:right;font-size:12px;color:#666;font-weight:500;">LST (Landsat)</th>
    <th style="padding:8px 10px;text-align:right;font-size:12px;color:#666;font-weight:500;">UHI z</th>
  </tr></thead>
  <tbody>{rows_html}</tbody>
</table>
<p style="font-family:sans-serif;font-size:11px;color:#888;margin-top:8px;">
LST = mean summer land surface temperature from Landsat 8/9 C2 L2 (June–Sept 2022–2024),
NASA ARSET methodology via Microsoft Planetary Computer. Z-score relative to NYC city-wide mean.
UHI z > +0.5 = meaningfully warmer than average.
</p>'''

display(HTML(html))

"""## Notes

### Data sources
| Layer | Source | Auth |
|---|---|---|
| 311 calls | NYC Open Data `erm2-nwe9` | None |
| Landsat C2 L2 LST | Microsoft Planetary Computer (`landsat-c2-l2`) | None (anon SAS token) |
| FDNY stations | NYC Open Data `hc8x-tcnd` | None |
| EMS stations | NYC Open Data `9ekd-5pvv` / `ji82-xba5` | None |
| HVI scores | NYC DOHMH `53vm-4bsj` | None |
| NTA boundaries | NYC Open Data `9nt8-h7nd` | None |

### LST conversion (ARSET / USGS)
```
LST_K = lwir11_DN × 0.00341802 + 149.0   # Kelvin
LST_C = LST_K - 273.15                    # Celsius
LST_F = LST_C × 9/5 + 32                 # Fahrenheit
```
Reference: USGS Landsat Collection 2 Level-2 Science Product Guide, Table 4-1.

### Why Planetary Computer beats OpenMeteo for this analysis
| | OpenMeteo ERA5 | Landsat C2 L2 (PC) |
|---|---|---|
| Resolution | ~9 km (ERA5 grid) | 30 m |
| Variable | 2m air temperature | Land surface temperature |
| UHI relevance | Moderate (captures regional pattern) | High (captures pavement vs park at street scale) |
| Auth required | None | None (anonymous) |
| Coverage | 2022–present | 1982–present |

### Potential next steps
- Add **NDVI** (Landsat bands 4+5) to correlate green cover with LST hotspots
- Add **Census tract** income/race equity join to the anomaly stations
- Filter to **post-heatwave events** (NOAA NWS heat advisory dates) to isolate extreme-event calls
- Compare against NYC's **Stormwater Flood Maps** to identify stations facing compound flood+heat risk
"""